[env]
GODOT4_BIN = { value = "C:/software/godot-custom/godot.windows.editor.x86_64.exe", relative = false }
LIBCLANG_PATH = { value = "C:/dev/LLVM/bin", relative = false }

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-pthread",
    "-C", "target-feature=+atomics",
    "-C", "link-args=-sSIDE_MODULE=2",
    "-Zlink-native-libraries=no",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
]
